{% set version = '1.01-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-flashclust
  version: {{ version|replace("-", "_") }}

source:
  fn: flashClust_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/flashClust_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/flashClust/flashClust_{{ version }}.tar.gz
  sha256: 48a7849bb86530465ff3fbfac1c273f0df4b846e67d5eee87187d250c8bf9450

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('flashClust')"  # [not win]
    - "\"%R%\" -e \"library('flashClust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=flashClust
  license: GPL (>= 2)
  summary: Fast implementation of hierarchical clustering
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
