travis:
  secure:
    BINSTAR_TOKEN: j0AUB8kLFePVecVkHfPSRl/VPNDY9ZeSly1c6cQvrttJwja199x07K5cII6Yejw4ta+HX4irW2E3/KJ3RLYg7IMA9or5WD/gIBbvvxZyng/vyxhOGETlSzMOGbG7TwSgAhRDZrnOv8G4w1zbIRvpaocdEM1eJw9aLL1xDlCCFXjQoh14ht6LgpTbAwqLKOdaGTyyN5+ityncXTkih8VrClz8Q00pMOTpKEFpRu9olWvdU+GOyZZ2BvVX69zdY5L5CbReV8aeklFtlTgbSA3N5OjsJbg0iiPrSyh3jUVP8fiKBk7SdI5OP5/xJ/8M+HmNTlF8ZZGCEy/w492dDYe5uFMETcF5hn5tj4o0ZvtfiuDe5mcOKmo53o92OEytINYu+pDfM7b+dSwVS2ZT8zYHCMTC5MBzFctZCT58cl6JN+XnPix1eKO8BYN7w3YcHD6hOTM5skVDy8rg6RoIFU/hgdHIxdQGB0JCUjWRxHSWVtQVU0g2wghJyEN+qwh2HvItybm71RzvC4Q4SeBbbsqXLHyoCIj7Bfnt4Hx9Yo69QMn3ncbx0VjwoswPL/fxn46uW07Sv4ngI+MAetoXM+3tuPZstIe5DpMq4/v/ptmayK5yhihBShlC+gHa+Bi7mRWKsA1+0hOkXyS/mMaU+lPYTQ+U+bbUF73By22Va+66Sa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
