appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: KpMJF52OVTjDvmL7uGyDmCC3iHJR7DjadMSoulghdXMGeEi9BE4HnCXWx0Aid+wLSs4ijnNW/lVDEfJduAdRaZprsFAQlN9lCJNMlorVV7ztvU4VbKqsAxhJQ8dnRQ7nOa2ovxONtjnj+JjJBLHQAdOkU1WxsNEFl+QW2Tozi2ZCir82uzGDt3YX8xYsLyCB2qwb2BLy8f9s3bNwg0U0CBe2lxV48TmD23qBJL3E7ZwuIXMtBWM2TKSnDyfFGmehJzK4Gd8BnsOURCVmb4wW/97QIiYQVxcSgijyJrhcJJnnI+lAwQxknp3nSGPH5AfO8JH35Kvus7uso/uhFzaZCVho+fmQH2CQi5fZ3MIq8MuIYjl10jv3cNHj5WV9m1tcDJWPklcLsID6Z0AUQ0MZQug43EiEPZ3IoxVM2258b9RhLVLInkHoPNOSKPmdQhtJNOqzAnTDcU8r6m8T9s5XV1cdbN1pT5NqGLIDJNXuIwRnmM6Nyrs5u+PQz8ySNkNN9A9vyfCuTnJhxURy8xl/qoMjoISAWOhkm+hpUiVix9DFgvhxcRfASMEZtuwOcdLFBm+W70BYiJNDvozb4Qb9nAaDXaEKiipX1gF89a18sEmND1+pBOh/MBCUNGUuRTpyRHJYsQg4JFY7cfuhUJ59OobHeWiU/TD5UHqp/sc6tt4=}
bot:
  automerge: true
